### ISSUE TITLE
Search no longer working

### ISSUE THREAD

**Issue by cartev** [michalczaplinski/pitchfork#3]
Pitchfork Site Redesign has made search() invalid

Searching produces a HTTP Error 404: Not Found on line 197 in pitchfork.py:
>>>response = urlopen(request)

From what I have noticed, the search url has changed and no longer includes 'ac/' in the static url you append queries to in 'http://pitchfork.com/search/ac/?query='

**Comment by michalczaplinski** [comment]
ah, i see it now. I haven't really kept the repo up to date, TBH.

Do you want to make the pull request with a fix? Otherwise, I ll probably fix that when I have a moment of time.

**Comment by aristeia** [comment]
Unfortunately, it's more than just the "/ac/" part of the URL. I forked to try the same fix, and ran into more JSON decoding issues after doing so. I'll look into it a bit more to see how much work needs to be done to get this working with Pitchforks new search page style.

**Comment by michalczaplinski** [comment]
fixed in #5 .
